### PR TITLE
Basic support for MPTS

### PR DESCRIPTION
**Pull request by stilldavid**
Contains a **breaking change**:

Removes `pat.ProgramMapPid()` and `pat.ProgramNumber()` in favor of a single `pat.ProgramMap()` that returns a `map[uint16]uint16` of the program numbers and associated PIDs.

That said, it's easy to keep the methods around if they are needed or wanted, but I think returning the map is probably more correct.

### CODE REVIEW

**Comment by guygrigsby** [comment]
- `ProgramMapPid()` and `ProgramNumber()` methods should remain with behavior unchanged. They could pull from the first entry in the programMap. Each method should be commented that they will be deprecated and then in the near future we will remove them.
- Please add test cases to test the new behavior.
- Finally, don't forget to sign the [CLA](https://github.com/Comcast/gots/blob/master/CLA.pdf). We can't merge it until it is signed. You can send it to me at guy_grigsby@cable.comcast.com

**Comment by BlakeOrth** [comment]
@guygrigsby In my opinion `ProgramMapPid()` and `ProgramNumber()` need to be modified to work as they do today, but only if the stream is actually SPTS.  It would be nice if the function definitions supported returning an error, but they do not.  For the time being we could return `8192` for the PID (parsing will always fail because stuffing) and `0` for the program number in the case of MPTS.  Thoughts?

**Comment by guygrigsby** [comment]
@BlakeOrth Sure, I can get behind that. Only because it's temporary though.

**Comment by stilldavid** [comment]
> Only because it's temporary though.

Famous last words :)

Sounds okay, though - I'll make the changes.

**Pull request merged**
